#!/bin/bash

cd
echo ""
echo "Сlique em permitir para prosseguir"
termux-setup-storage & sleep 4 &>/dev/null
while true; do
if [ -e storage ]; then
rm -rf /sdcard/Box64-Ptbr
break
else
echo "se voce negou a permissão,permita nas configurações do termux agora"
fi
sleep 1
done
mkdir -p /sdcard/Box64-Ptbr
pkg clean
pkg update -y
pkg upgrade -y
sleep 2
echo ""
echo "Instalando pacotes"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
rm -rf $HOME/Box64-Ptbr
mkdir -p $HOME/Box64-Ptbr
cd $HOME/Box64-Ptbr
wget https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/releases/download/Package/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb

echo ""
echo "Baixando rootfs..."
cd $HOME/Box64-Ptbr
wget -q --show-progress https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/releases/download/Package/rootfs.tar.xz

echo ""
echo "Descompactando Rootfs aguarde.."
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/termux-box/ubuntu-fs/opt
wget https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/releases/download/Package/scripts.tar.gz &>/dev/null
tar -xf scripts.tar.gz
rm -rf scripts.tar.gz

cd $HOME/Box64-Ptbr/
wget -N https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/raw/main/iniciar-box &>/dev/null
chmod +x iniciar-box
mv iniciar-box $PREFIX/bin/
wget -N https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/raw/main/start-proot.sh &>/dev/null
wget -N https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/raw/main/start-chroot.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

echo "Finalizando instalação"

cd $HOME/Box64-Ptbr/ubuntu-fs
wget -q --show-progress https://github.com/GabrilXX/TermuxX11-box64-86-Ptbr/releases/download/Package/patch.tar.xz
tar -xf patch.tar.xz
rm -rf patch.tar.xz
cd
rm -rf "$0"
. $PREFIX/bin/iniciar-box
